---
elasticsearch:
  build: docker-compose.d/elasticsearch
  ports:
    - "9200:9200"
  expose:
    - "9200"

kibana:
  build: docker-compose.d/kibana
  ports:
    - "5601:5601"
  expose:
    - "5601"
  links:
    - elasticsearch

debian:
  build: docker-compose.d/debian
  volumes:
    - .:/mnt/packagebeat:ro
  links:
    - elasticsearch

fedora:
  build: docker-compose.d/fedora
  volumes:
    - .:/mnt/packagebeat:ro
  links:
    - elasticsearch
